// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	audit "github.com/alxaxenov/url-shortener/tree/v2/internal/worker/audit"

	mock "github.com/stretchr/testify/mock"
)

// AuditPublisher is an autogenerated mock type for the AuditPublisher type
type AuditPublisher struct {
	mock.Mock
}

type AuditPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditPublisher) EXPECT() *AuditPublisher_Expecter {
	return &AuditPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: action, userID, URL
func (_m *AuditPublisher) Publish(action audit.ActionType, userID int, URL string) {
	_m.Called(action, userID, URL)
}

// AuditPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type AuditPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - action audit.ActionType
//   - userID int
//   - URL string
func (_e *AuditPublisher_Expecter) Publish(action interface{}, userID interface{}, URL interface{}) *AuditPublisher_Publish_Call {
	return &AuditPublisher_Publish_Call{Call: _e.mock.On("Publish", action, userID, URL)}
}

func (_c *AuditPublisher_Publish_Call) Run(run func(action audit.ActionType, userID int, URL string)) *AuditPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(audit.ActionType), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *AuditPublisher_Publish_Call) Return() *AuditPublisher_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuditPublisher_Publish_Call) RunAndReturn(run func(audit.ActionType, int, string)) *AuditPublisher_Publish_Call {
	_c.Run(run)
	return _c
}

// NewAuditPublisher creates a new instance of AuditPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditPublisher {
	mock := &AuditPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
