// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/alxaxenov/url-shortener/tree/v2/internal/model"
)

// ShortenerService is an autogenerated mock type for the ShortenerService type
type ShortenerService struct {
	mock.Mock
}

type ShortenerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShortenerService) EXPECT() *ShortenerService_Expecter {
	return &ShortenerService_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function with given fields: _a0, _a1, _a2
func (_m *ShortenerService) AddURL(_a0 context.Context, _a1 string, _a2 int) (string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerService_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type ShortenerService_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 int
func (_e *ShortenerService_Expecter) AddURL(_a0 interface{}, _a1 interface{}, _a2 interface{}) *ShortenerService_AddURL_Call {
	return &ShortenerService_AddURL_Call{Call: _e.mock.On("AddURL", _a0, _a1, _a2)}
}

func (_c *ShortenerService_AddURL_Call) Run(run func(_a0 context.Context, _a1 string, _a2 int)) *ShortenerService_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ShortenerService_AddURL_Call) Return(_a0 string, _a1 error) *ShortenerService_AddURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerService_AddURL_Call) RunAndReturn(run func(context.Context, string, int) (string, error)) *ShortenerService_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// AppendDelete provides a mock function with given fields: _a0, _a1
func (_m *ShortenerService) AppendDelete(_a0 int, _a1 model.DeleteURLs) {
	_m.Called(_a0, _a1)
}

// ShortenerService_AppendDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendDelete'
type ShortenerService_AppendDelete_Call struct {
	*mock.Call
}

// AppendDelete is a helper method to define mock.On call
//   - _a0 int
//   - _a1 model.DeleteURLs
func (_e *ShortenerService_Expecter) AppendDelete(_a0 interface{}, _a1 interface{}) *ShortenerService_AppendDelete_Call {
	return &ShortenerService_AppendDelete_Call{Call: _e.mock.On("AppendDelete", _a0, _a1)}
}

func (_c *ShortenerService_AppendDelete_Call) Run(run func(_a0 int, _a1 model.DeleteURLs)) *ShortenerService_AppendDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(model.DeleteURLs))
	})
	return _c
}

func (_c *ShortenerService_AppendDelete_Call) Return() *ShortenerService_AppendDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShortenerService_AppendDelete_Call) RunAndReturn(run func(int, model.DeleteURLs)) *ShortenerService_AppendDelete_Call {
	_c.Run(run)
	return _c
}

// GetURL provides a mock function with given fields: _a0, _a1
func (_m *ShortenerService) GetURL(_a0 context.Context, _a1 string) (string, bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ShortenerService_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type ShortenerService_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ShortenerService_Expecter) GetURL(_a0 interface{}, _a1 interface{}) *ShortenerService_GetURL_Call {
	return &ShortenerService_GetURL_Call{Call: _e.mock.On("GetURL", _a0, _a1)}
}

func (_c *ShortenerService_GetURL_Call) Run(run func(_a0 context.Context, _a1 string)) *ShortenerService_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShortenerService_GetURL_Call) Return(_a0 string, _a1 bool, _a2 error) *ShortenerService_GetURL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ShortenerService_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *ShortenerService_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: _a0, _a1, _a2
func (_m *ShortenerService) SaveBatch(_a0 context.Context, _a1 model.LoadBatchRequest, _a2 int) ([]model.BatchResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 []model.BatchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LoadBatchRequest, int) ([]model.BatchResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LoadBatchRequest, int) []model.BatchResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BatchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LoadBatchRequest, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerService_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type ShortenerService_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.LoadBatchRequest
//   - _a2 int
func (_e *ShortenerService_Expecter) SaveBatch(_a0 interface{}, _a1 interface{}, _a2 interface{}) *ShortenerService_SaveBatch_Call {
	return &ShortenerService_SaveBatch_Call{Call: _e.mock.On("SaveBatch", _a0, _a1, _a2)}
}

func (_c *ShortenerService_SaveBatch_Call) Run(run func(_a0 context.Context, _a1 model.LoadBatchRequest, _a2 int)) *ShortenerService_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LoadBatchRequest), args[2].(int))
	})
	return _c
}

func (_c *ShortenerService_SaveBatch_Call) Return(_a0 []model.BatchResponse, _a1 error) *ShortenerService_SaveBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerService_SaveBatch_Call) RunAndReturn(run func(context.Context, model.LoadBatchRequest, int) ([]model.BatchResponse, error)) *ShortenerService_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UserURLs provides a mock function with given fields: _a0, _a1
func (_m *ShortenerService) UserURLs(_a0 context.Context, _a1 int) ([]model.UserURLs, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserURLs")
	}

	var r0 []model.UserURLs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.UserURLs, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.UserURLs); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserURLs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerService_UserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserURLs'
type ShortenerService_UserURLs_Call struct {
	*mock.Call
}

// UserURLs is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *ShortenerService_Expecter) UserURLs(_a0 interface{}, _a1 interface{}) *ShortenerService_UserURLs_Call {
	return &ShortenerService_UserURLs_Call{Call: _e.mock.On("UserURLs", _a0, _a1)}
}

func (_c *ShortenerService_UserURLs_Call) Run(run func(_a0 context.Context, _a1 int)) *ShortenerService_UserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ShortenerService_UserURLs_Call) Return(_a0 []model.UserURLs, _a1 error) *ShortenerService_UserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerService_UserURLs_Call) RunAndReturn(run func(context.Context, int) ([]model.UserURLs, error)) *ShortenerService_UserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewShortenerService creates a new instance of ShortenerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenerService {
	mock := &ShortenerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
