// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ISemaphore is an autogenerated mock type for the ISemaphore type
type ISemaphore struct {
	mock.Mock
}

type ISemaphore_Expecter struct {
	mock *mock.Mock
}

func (_m *ISemaphore) EXPECT() *ISemaphore_Expecter {
	return &ISemaphore_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with no fields
func (_m *ISemaphore) Acquire() {
	_m.Called()
}

// ISemaphore_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type ISemaphore_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
func (_e *ISemaphore_Expecter) Acquire() *ISemaphore_Acquire_Call {
	return &ISemaphore_Acquire_Call{Call: _e.mock.On("Acquire")}
}

func (_c *ISemaphore_Acquire_Call) Run(run func()) *ISemaphore_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ISemaphore_Acquire_Call) Return() *ISemaphore_Acquire_Call {
	_c.Call.Return()
	return _c
}

func (_c *ISemaphore_Acquire_Call) RunAndReturn(run func()) *ISemaphore_Acquire_Call {
	_c.Run(run)
	return _c
}

// Release provides a mock function with no fields
func (_m *ISemaphore) Release() {
	_m.Called()
}

// ISemaphore_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type ISemaphore_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *ISemaphore_Expecter) Release() *ISemaphore_Release_Call {
	return &ISemaphore_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *ISemaphore_Release_Call) Run(run func()) *ISemaphore_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ISemaphore_Release_Call) Return() *ISemaphore_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *ISemaphore_Release_Call) RunAndReturn(run func()) *ISemaphore_Release_Call {
	_c.Run(run)
	return _c
}

// NewISemaphore creates a new instance of ISemaphore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISemaphore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISemaphore {
	mock := &ISemaphore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
