// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/alxaxenov/url-shortener/tree/v2/internal/model"
)

// IShortenerService is an autogenerated mock type for the IShortenerService type
type IShortenerService struct {
	mock.Mock
}

type IShortenerService_Expecter struct {
	mock *mock.Mock
}

func (_m *IShortenerService) EXPECT() *IShortenerService_Expecter {
	return &IShortenerService_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function with given fields: _a0, _a1, _a2
func (_m *IShortenerService) AddURL(_a0 context.Context, _a1 string, _a2 int) (string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IShortenerService_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type IShortenerService_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 int
func (_e *IShortenerService_Expecter) AddURL(_a0 interface{}, _a1 interface{}, _a2 interface{}) *IShortenerService_AddURL_Call {
	return &IShortenerService_AddURL_Call{Call: _e.mock.On("AddURL", _a0, _a1, _a2)}
}

func (_c *IShortenerService_AddURL_Call) Run(run func(_a0 context.Context, _a1 string, _a2 int)) *IShortenerService_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *IShortenerService_AddURL_Call) Return(_a0 string, _a1 error) *IShortenerService_AddURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IShortenerService_AddURL_Call) RunAndReturn(run func(context.Context, string, int) (string, error)) *IShortenerService_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// AppendDelete provides a mock function with given fields: _a0, _a1
func (_m *IShortenerService) AppendDelete(_a0 int, _a1 model.DeleteURLs) {
	_m.Called(_a0, _a1)
}

// IShortenerService_AppendDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendDelete'
type IShortenerService_AppendDelete_Call struct {
	*mock.Call
}

// AppendDelete is a helper method to define mock.On call
//   - _a0 int
//   - _a1 model.DeleteURLs
func (_e *IShortenerService_Expecter) AppendDelete(_a0 interface{}, _a1 interface{}) *IShortenerService_AppendDelete_Call {
	return &IShortenerService_AppendDelete_Call{Call: _e.mock.On("AppendDelete", _a0, _a1)}
}

func (_c *IShortenerService_AppendDelete_Call) Run(run func(_a0 int, _a1 model.DeleteURLs)) *IShortenerService_AppendDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(model.DeleteURLs))
	})
	return _c
}

func (_c *IShortenerService_AppendDelete_Call) Return() *IShortenerService_AppendDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *IShortenerService_AppendDelete_Call) RunAndReturn(run func(int, model.DeleteURLs)) *IShortenerService_AppendDelete_Call {
	_c.Run(run)
	return _c
}

// GetURL provides a mock function with given fields: _a0, _a1
func (_m *IShortenerService) GetURL(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IShortenerService_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type IShortenerService_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *IShortenerService_Expecter) GetURL(_a0 interface{}, _a1 interface{}) *IShortenerService_GetURL_Call {
	return &IShortenerService_GetURL_Call{Call: _e.mock.On("GetURL", _a0, _a1)}
}

func (_c *IShortenerService_GetURL_Call) Run(run func(_a0 context.Context, _a1 string)) *IShortenerService_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IShortenerService_GetURL_Call) Return(_a0 string, _a1 error) *IShortenerService_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IShortenerService_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *IShortenerService_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: _a0, _a1, _a2
func (_m *IShortenerService) SaveBatch(_a0 context.Context, _a1 model.LoadBatchRequest, _a2 int) ([]model.BatchResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 []model.BatchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LoadBatchRequest, int) ([]model.BatchResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LoadBatchRequest, int) []model.BatchResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BatchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LoadBatchRequest, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IShortenerService_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type IShortenerService_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.LoadBatchRequest
//   - _a2 int
func (_e *IShortenerService_Expecter) SaveBatch(_a0 interface{}, _a1 interface{}, _a2 interface{}) *IShortenerService_SaveBatch_Call {
	return &IShortenerService_SaveBatch_Call{Call: _e.mock.On("SaveBatch", _a0, _a1, _a2)}
}

func (_c *IShortenerService_SaveBatch_Call) Run(run func(_a0 context.Context, _a1 model.LoadBatchRequest, _a2 int)) *IShortenerService_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LoadBatchRequest), args[2].(int))
	})
	return _c
}

func (_c *IShortenerService_SaveBatch_Call) Return(_a0 []model.BatchResponse, _a1 error) *IShortenerService_SaveBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IShortenerService_SaveBatch_Call) RunAndReturn(run func(context.Context, model.LoadBatchRequest, int) ([]model.BatchResponse, error)) *IShortenerService_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// URLsAndUsersCount provides a mock function with given fields: _a0
func (_m *IShortenerService) URLsAndUsersCount(_a0 context.Context) (int, int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for URLsAndUsersCount")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IShortenerService_URLsAndUsersCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URLsAndUsersCount'
type IShortenerService_URLsAndUsersCount_Call struct {
	*mock.Call
}

// URLsAndUsersCount is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *IShortenerService_Expecter) URLsAndUsersCount(_a0 interface{}) *IShortenerService_URLsAndUsersCount_Call {
	return &IShortenerService_URLsAndUsersCount_Call{Call: _e.mock.On("URLsAndUsersCount", _a0)}
}

func (_c *IShortenerService_URLsAndUsersCount_Call) Run(run func(_a0 context.Context)) *IShortenerService_URLsAndUsersCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IShortenerService_URLsAndUsersCount_Call) Return(_a0 int, _a1 int, _a2 error) *IShortenerService_URLsAndUsersCount_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IShortenerService_URLsAndUsersCount_Call) RunAndReturn(run func(context.Context) (int, int, error)) *IShortenerService_URLsAndUsersCount_Call {
	_c.Call.Return(run)
	return _c
}

// UserURLs provides a mock function with given fields: _a0, _a1
func (_m *IShortenerService) UserURLs(_a0 context.Context, _a1 int) ([]model.UserURLs, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserURLs")
	}

	var r0 []model.UserURLs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.UserURLs, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.UserURLs); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserURLs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IShortenerService_UserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserURLs'
type IShortenerService_UserURLs_Call struct {
	*mock.Call
}

// UserURLs is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *IShortenerService_Expecter) UserURLs(_a0 interface{}, _a1 interface{}) *IShortenerService_UserURLs_Call {
	return &IShortenerService_UserURLs_Call{Call: _e.mock.On("UserURLs", _a0, _a1)}
}

func (_c *IShortenerService_UserURLs_Call) Run(run func(_a0 context.Context, _a1 int)) *IShortenerService_UserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *IShortenerService_UserURLs_Call) Return(_a0 []model.UserURLs, _a1 error) *IShortenerService_UserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IShortenerService_UserURLs_Call) RunAndReturn(run func(context.Context, int) ([]model.UserURLs, error)) *IShortenerService_UserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewIShortenerService creates a new instance of IShortenerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIShortenerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IShortenerService {
	mock := &IShortenerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
