// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortenerService is an autogenerated mock type for the ShortenerService type
type ShortenerService struct {
	mock.Mock
}

type ShortenerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShortenerService) EXPECT() *ShortenerService_Expecter {
	return &ShortenerService_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function with given fields: _a0, _a1
func (_m *ShortenerService) AddURL(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerService_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type ShortenerService_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ShortenerService_Expecter) AddURL(_a0 interface{}, _a1 interface{}) *ShortenerService_AddURL_Call {
	return &ShortenerService_AddURL_Call{Call: _e.mock.On("AddURL", _a0, _a1)}
}

func (_c *ShortenerService_AddURL_Call) Run(run func(_a0 context.Context, _a1 string)) *ShortenerService_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShortenerService_AddURL_Call) Return(_a0 string, _a1 error) *ShortenerService_AddURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerService_AddURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *ShortenerService_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: _a0, _a1
func (_m *ShortenerService) GetURL(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerService_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type ShortenerService_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ShortenerService_Expecter) GetURL(_a0 interface{}, _a1 interface{}) *ShortenerService_GetURL_Call {
	return &ShortenerService_GetURL_Call{Call: _e.mock.On("GetURL", _a0, _a1)}
}

func (_c *ShortenerService_GetURL_Call) Run(run func(_a0 context.Context, _a1 string)) *ShortenerService_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShortenerService_GetURL_Call) Return(_a0 string, _a1 error) *ShortenerService_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerService_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *ShortenerService_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewShortenerService creates a new instance of ShortenerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenerService {
	mock := &ShortenerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
