// Code generated by mockery v2.53.6. DO NOT EDIT.

package memory

import mock "github.com/stretchr/testify/mock"

// MockIFactoryReader is an autogenerated mock type for the IFactoryReader type
type MockIFactoryReader struct {
	mock.Mock
}

type MockIFactoryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFactoryReader) EXPECT() *MockIFactoryReader_Expecter {
	return &MockIFactoryReader_Expecter{mock: &_m.Mock}
}

// NewReader provides a mock function with given fields: _a0
func (_m *MockIFactoryReader) NewReader(_a0 string) (Reader, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NewReader")
	}

	var r0 Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (Reader, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) Reader); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFactoryReader_NewReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewReader'
type MockIFactoryReader_NewReader_Call struct {
	*mock.Call
}

// NewReader is a helper method to define mock.On call
//   - _a0 string
func (_e *MockIFactoryReader_Expecter) NewReader(_a0 interface{}) *MockIFactoryReader_NewReader_Call {
	return &MockIFactoryReader_NewReader_Call{Call: _e.mock.On("NewReader", _a0)}
}

func (_c *MockIFactoryReader_NewReader_Call) Run(run func(_a0 string)) *MockIFactoryReader_NewReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIFactoryReader_NewReader_Call) Return(_a0 Reader, _a1 error) *MockIFactoryReader_NewReader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFactoryReader_NewReader_Call) RunAndReturn(run func(string) (Reader, error)) *MockIFactoryReader_NewReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIFactoryReader creates a new instance of MockIFactoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFactoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFactoryReader {
	mock := &MockIFactoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
