// Code generated by mockery v2.53.6. DO NOT EDIT.

package memory

import mock "github.com/stretchr/testify/mock"

// MockIFactoryWriter is an autogenerated mock type for the IFactoryWriter type
type MockIFactoryWriter struct {
	mock.Mock
}

type MockIFactoryWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFactoryWriter) EXPECT() *MockIFactoryWriter_Expecter {
	return &MockIFactoryWriter_Expecter{mock: &_m.Mock}
}

// NewWriter provides a mock function with given fields: _a0
func (_m *MockIFactoryWriter) NewWriter(_a0 string) (Writer, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NewWriter")
	}

	var r0 Writer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (Writer, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) Writer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Writer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFactoryWriter_NewWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWriter'
type MockIFactoryWriter_NewWriter_Call struct {
	*mock.Call
}

// NewWriter is a helper method to define mock.On call
//   - _a0 string
func (_e *MockIFactoryWriter_Expecter) NewWriter(_a0 interface{}) *MockIFactoryWriter_NewWriter_Call {
	return &MockIFactoryWriter_NewWriter_Call{Call: _e.mock.On("NewWriter", _a0)}
}

func (_c *MockIFactoryWriter_NewWriter_Call) Run(run func(_a0 string)) *MockIFactoryWriter_NewWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIFactoryWriter_NewWriter_Call) Return(_a0 Writer, _a1 error) *MockIFactoryWriter_NewWriter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFactoryWriter_NewWriter_Call) RunAndReturn(run func(string) (Writer, error)) *MockIFactoryWriter_NewWriter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIFactoryWriter creates a new instance of MockIFactoryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFactoryWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFactoryWriter {
	mock := &MockIFactoryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
