// Code generated by mockery v2.53.5. DO NOT EDIT.

package memory

import mock "github.com/stretchr/testify/mock"

// MockWriterInt is an autogenerated mock type for the WriterInt type
type MockWriterInt struct {
	mock.Mock
}

type MockWriterInt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriterInt) EXPECT() *MockWriterInt_Expecter {
	return &MockWriterInt_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockWriterInt) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriterInt_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWriterInt_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWriterInt_Expecter) Close() *MockWriterInt_Close_Call {
	return &MockWriterInt_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWriterInt_Close_Call) Run(run func()) *MockWriterInt_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWriterInt_Close_Call) Return(_a0 error) *MockWriterInt_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriterInt_Close_Call) RunAndReturn(run func() error) *MockWriterInt_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *MockWriterInt) Write(_a0 []byte) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWriterInt_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWriterInt_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 []byte
func (_e *MockWriterInt_Expecter) Write(_a0 interface{}) *MockWriterInt_Write_Call {
	return &MockWriterInt_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *MockWriterInt_Write_Call) Run(run func(_a0 []byte)) *MockWriterInt_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockWriterInt_Write_Call) Return(_a0 int, _a1 error) *MockWriterInt_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWriterInt_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockWriterInt_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriterInt creates a new instance of MockWriterInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriterInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriterInt {
	mock := &MockWriterInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
