// Code generated by mockery v2.53.5. DO NOT EDIT.

package memory

import mock "github.com/stretchr/testify/mock"

// MockFactoryReaderInt is an autogenerated mock type for the FactoryReaderInt type
type MockFactoryReaderInt struct {
	mock.Mock
}

type MockFactoryReaderInt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactoryReaderInt) EXPECT() *MockFactoryReaderInt_Expecter {
	return &MockFactoryReaderInt_Expecter{mock: &_m.Mock}
}

// NewReader provides a mock function with given fields: _a0
func (_m *MockFactoryReaderInt) NewReader(_a0 string) (ReaderInt, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NewReader")
	}

	var r0 ReaderInt
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ReaderInt, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) ReaderInt); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ReaderInt)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFactoryReaderInt_NewReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewReader'
type MockFactoryReaderInt_NewReader_Call struct {
	*mock.Call
}

// NewReader is a helper method to define mock.On call
//   - _a0 string
func (_e *MockFactoryReaderInt_Expecter) NewReader(_a0 interface{}) *MockFactoryReaderInt_NewReader_Call {
	return &MockFactoryReaderInt_NewReader_Call{Call: _e.mock.On("NewReader", _a0)}
}

func (_c *MockFactoryReaderInt_NewReader_Call) Run(run func(_a0 string)) *MockFactoryReaderInt_NewReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFactoryReaderInt_NewReader_Call) Return(_a0 ReaderInt, _a1 error) *MockFactoryReaderInt_NewReader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFactoryReaderInt_NewReader_Call) RunAndReturn(run func(string) (ReaderInt, error)) *MockFactoryReaderInt_NewReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFactoryReaderInt creates a new instance of MockFactoryReaderInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactoryReaderInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactoryReaderInt {
	mock := &MockFactoryReaderInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
