// Code generated by mockery v2.53.5. DO NOT EDIT.

package memory

import mock "github.com/stretchr/testify/mock"

// MockFactoryWriterInt is an autogenerated mock type for the FactoryWriterInt type
type MockFactoryWriterInt struct {
	mock.Mock
}

type MockFactoryWriterInt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactoryWriterInt) EXPECT() *MockFactoryWriterInt_Expecter {
	return &MockFactoryWriterInt_Expecter{mock: &_m.Mock}
}

// NewWriter provides a mock function with given fields: _a0
func (_m *MockFactoryWriterInt) NewWriter(_a0 string) (WriterInt, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NewWriter")
	}

	var r0 WriterInt
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (WriterInt, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) WriterInt); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(WriterInt)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFactoryWriterInt_NewWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWriter'
type MockFactoryWriterInt_NewWriter_Call struct {
	*mock.Call
}

// NewWriter is a helper method to define mock.On call
//   - _a0 string
func (_e *MockFactoryWriterInt_Expecter) NewWriter(_a0 interface{}) *MockFactoryWriterInt_NewWriter_Call {
	return &MockFactoryWriterInt_NewWriter_Call{Call: _e.mock.On("NewWriter", _a0)}
}

func (_c *MockFactoryWriterInt_NewWriter_Call) Run(run func(_a0 string)) *MockFactoryWriterInt_NewWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFactoryWriterInt_NewWriter_Call) Return(_a0 WriterInt, _a1 error) *MockFactoryWriterInt_NewWriter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFactoryWriterInt_NewWriter_Call) RunAndReturn(run func(string) (WriterInt, error)) *MockFactoryWriterInt_NewWriter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFactoryWriterInt creates a new instance of MockFactoryWriterInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactoryWriterInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactoryWriterInt {
	mock := &MockFactoryWriterInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
