// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alxaxenov/url-shortener/tree/v2/internal/model"
	mock "github.com/stretchr/testify/mock"

	repositorymodel "github.com/alxaxenov/url-shortener/tree/v2/internal/repository/model"
)

// ShortenerRepo is an autogenerated mock type for the ShortenerRepo type
type ShortenerRepo struct {
	mock.Mock
}

type ShortenerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ShortenerRepo) EXPECT() *ShortenerRepo_Expecter {
	return &ShortenerRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: _a0
func (_m *ShortenerRepo) CreateUser(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type ShortenerRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ShortenerRepo_Expecter) CreateUser(_a0 interface{}) *ShortenerRepo_CreateUser_Call {
	return &ShortenerRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", _a0)}
}

func (_c *ShortenerRepo_CreateUser_Call) Run(run func(_a0 context.Context)) *ShortenerRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ShortenerRepo_CreateUser_Call) Return(_a0 int, _a1 error) *ShortenerRepo_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerRepo_CreateUser_Call) RunAndReturn(run func(context.Context) (int, error)) *ShortenerRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteURLs provides a mock function with given fields: _a0, _a1
func (_m *ShortenerRepo) DeleteURLs(_a0 context.Context, _a1 *model.DeleteRequest) (int, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURLs")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.DeleteRequest) (int, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.DeleteRequest) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.DeleteRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerRepo_DeleteURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURLs'
type ShortenerRepo_DeleteURLs_Call struct {
	*mock.Call
}

// DeleteURLs is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *model.DeleteRequest
func (_e *ShortenerRepo_Expecter) DeleteURLs(_a0 interface{}, _a1 interface{}) *ShortenerRepo_DeleteURLs_Call {
	return &ShortenerRepo_DeleteURLs_Call{Call: _e.mock.On("DeleteURLs", _a0, _a1)}
}

func (_c *ShortenerRepo_DeleteURLs_Call) Run(run func(_a0 context.Context, _a1 *model.DeleteRequest)) *ShortenerRepo_DeleteURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.DeleteRequest))
	})
	return _c
}

func (_c *ShortenerRepo_DeleteURLs_Call) Return(_a0 int, _a1 error) *ShortenerRepo_DeleteURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerRepo_DeleteURLs_Call) RunAndReturn(run func(context.Context, *model.DeleteRequest) (int, error)) *ShortenerRepo_DeleteURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetValue provides a mock function with given fields: _a0, _a1
func (_m *ShortenerRepo) GetValue(_a0 context.Context, _a1 string) (string, bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetValue")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ShortenerRepo_GetValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValue'
type ShortenerRepo_GetValue_Call struct {
	*mock.Call
}

// GetValue is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ShortenerRepo_Expecter) GetValue(_a0 interface{}, _a1 interface{}) *ShortenerRepo_GetValue_Call {
	return &ShortenerRepo_GetValue_Call{Call: _e.mock.On("GetValue", _a0, _a1)}
}

func (_c *ShortenerRepo_GetValue_Call) Run(run func(_a0 context.Context, _a1 string)) *ShortenerRepo_GetValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShortenerRepo_GetValue_Call) Return(_a0 string, _a1 bool, _a2 error) *ShortenerRepo_GetValue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ShortenerRepo_GetValue_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *ShortenerRepo_GetValue_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: _a0, _a1, _a2
func (_m *ShortenerRepo) SaveBatch(_a0 context.Context, _a1 []repositorymodel.UploadBatch, _a2 int) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repositorymodel.UploadBatch, int) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShortenerRepo_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type ShortenerRepo_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []repositorymodel.UploadBatch
//   - _a2 int
func (_e *ShortenerRepo_Expecter) SaveBatch(_a0 interface{}, _a1 interface{}, _a2 interface{}) *ShortenerRepo_SaveBatch_Call {
	return &ShortenerRepo_SaveBatch_Call{Call: _e.mock.On("SaveBatch", _a0, _a1, _a2)}
}

func (_c *ShortenerRepo_SaveBatch_Call) Run(run func(_a0 context.Context, _a1 []repositorymodel.UploadBatch, _a2 int)) *ShortenerRepo_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]repositorymodel.UploadBatch), args[2].(int))
	})
	return _c
}

func (_c *ShortenerRepo_SaveBatch_Call) Return(_a0 error) *ShortenerRepo_SaveBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShortenerRepo_SaveBatch_Call) RunAndReturn(run func(context.Context, []repositorymodel.UploadBatch, int) error) *ShortenerRepo_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SetValue provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *ShortenerRepo) SetValue(_a0 context.Context, _a1 string, _a2 string, _a3 int) (string, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for SetValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (string, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) string); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerRepo_SetValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetValue'
type ShortenerRepo_SetValue_Call struct {
	*mock.Call
}

// SetValue is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 int
func (_e *ShortenerRepo_Expecter) SetValue(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *ShortenerRepo_SetValue_Call {
	return &ShortenerRepo_SetValue_Call{Call: _e.mock.On("SetValue", _a0, _a1, _a2, _a3)}
}

func (_c *ShortenerRepo_SetValue_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 int)) *ShortenerRepo_SetValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *ShortenerRepo_SetValue_Call) Return(_a0 string, _a1 error) *ShortenerRepo_SetValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerRepo_SetValue_Call) RunAndReturn(run func(context.Context, string, string, int) (string, error)) *ShortenerRepo_SetValue_Call {
	_c.Call.Return(run)
	return _c
}

// UserURLs provides a mock function with given fields: _a0, _a1
func (_m *ShortenerRepo) UserURLs(_a0 context.Context, _a1 int) ([]model.UserURLs, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserURLs")
	}

	var r0 []model.UserURLs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.UserURLs, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.UserURLs); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserURLs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerRepo_UserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserURLs'
type ShortenerRepo_UserURLs_Call struct {
	*mock.Call
}

// UserURLs is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *ShortenerRepo_Expecter) UserURLs(_a0 interface{}, _a1 interface{}) *ShortenerRepo_UserURLs_Call {
	return &ShortenerRepo_UserURLs_Call{Call: _e.mock.On("UserURLs", _a0, _a1)}
}

func (_c *ShortenerRepo_UserURLs_Call) Run(run func(_a0 context.Context, _a1 int)) *ShortenerRepo_UserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ShortenerRepo_UserURLs_Call) Return(_a0 []model.UserURLs, _a1 error) *ShortenerRepo_UserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerRepo_UserURLs_Call) RunAndReturn(run func(context.Context, int) ([]model.UserURLs, error)) *ShortenerRepo_UserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewShortenerRepo creates a new instance of ShortenerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenerRepo {
	mock := &ShortenerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
