// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortenerServiceInt creates a new instance of MockShortenerServiceInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortenerServiceInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortenerServiceInt {
	mock := &MockShortenerServiceInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortenerServiceInt is an autogenerated mock type for the ShortenerServiceInt type
type MockShortenerServiceInt struct {
	mock.Mock
}

type MockShortenerServiceInt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortenerServiceInt) EXPECT() *MockShortenerServiceInt_Expecter {
	return &MockShortenerServiceInt_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function for the type MockShortenerServiceInt
func (_mock *MockShortenerServiceInt) AddURL(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortenerServiceInt_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type MockShortenerServiceInt_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - s string
func (_e *MockShortenerServiceInt_Expecter) AddURL(s interface{}) *MockShortenerServiceInt_AddURL_Call {
	return &MockShortenerServiceInt_AddURL_Call{Call: _e.mock.On("AddURL", s)}
}

func (_c *MockShortenerServiceInt_AddURL_Call) Run(run func(s string)) *MockShortenerServiceInt_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortenerServiceInt_AddURL_Call) Return(s1 string, err error) *MockShortenerServiceInt_AddURL_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockShortenerServiceInt_AddURL_Call) RunAndReturn(run func(s string) (string, error)) *MockShortenerServiceInt_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type MockShortenerServiceInt
func (_mock *MockShortenerServiceInt) GetURL(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortenerServiceInt_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockShortenerServiceInt_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - s string
func (_e *MockShortenerServiceInt_Expecter) GetURL(s interface{}) *MockShortenerServiceInt_GetURL_Call {
	return &MockShortenerServiceInt_GetURL_Call{Call: _e.mock.On("GetURL", s)}
}

func (_c *MockShortenerServiceInt_GetURL_Call) Run(run func(s string)) *MockShortenerServiceInt_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortenerServiceInt_GetURL_Call) Return(s1 string, err error) *MockShortenerServiceInt_GetURL_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockShortenerServiceInt_GetURL_Call) RunAndReturn(run func(s string) (string, error)) *MockShortenerServiceInt_GetURL_Call {
	_c.Call.Return(run)
	return _c
}
