// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Ihasher is an autogenerated mock type for the Ihasher type
type Ihasher struct {
	mock.Mock
}

type Ihasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Ihasher) EXPECT() *Ihasher_Expecter {
	return &Ihasher_Expecter{mock: &_m.Mock}
}

// GetShort provides a mock function with no fields
func (_m *Ihasher) GetShort() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShort")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ihasher_GetShort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShort'
type Ihasher_GetShort_Call struct {
	*mock.Call
}

// GetShort is a helper method to define mock.On call
func (_e *Ihasher_Expecter) GetShort() *Ihasher_GetShort_Call {
	return &Ihasher_GetShort_Call{Call: _e.mock.On("GetShort")}
}

func (_c *Ihasher_GetShort_Call) Run(run func()) *Ihasher_GetShort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Ihasher_GetShort_Call) Return(_a0 string, _a1 error) *Ihasher_GetShort_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Ihasher_GetShort_Call) RunAndReturn(run func() (string, error)) *Ihasher_GetShort_Call {
	_c.Call.Return(run)
	return _c
}

// NewIhasher creates a new instance of Ihasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIhasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Ihasher {
	mock := &Ihasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
